### ISSUE TITLE
Incorrect replacement of host domain by /

### ISSUE THREAD

**Issue by sdmcraft** [adobe/helix-importer#186]
**Description**
While importing pages,  host domain is replaced by `/` everywhere. This is expected for `href`'s, but not at places like `textContent` of `a` tags or other places like query parameters of embedded links etc. 

**To Reproduce**
1. Import the following page https://www.sunstar-engineering.com/news/20190930
2. Observe that in the imported document, `https://www.sunstar-engineering.com` in text is replaced by `/`
![image](https://github.com/adobe/helix-importer/assets/1191451/820390cd-4466-4100-9a3a-18ad86ee18d2)
3. Similar behavior observed for url parameters
![image](https://github.com/adobe/helix-importer/assets/1191451/21d53a6c-4fad-4240-a159-60553ba21659)

**Expected behavior**
host domain should not be replaced by `/` in such instances as cited above

**Version:**
v14.21.4

**Additional context**
[Related conversation](https://cq-dev.slack.com/archives/C058KBHLBGR/p1689305424669739)

**Comment by tripodsan** [comment]
fixed with https://github.com/adobe/helix-cli/releases/tag/v14.24.7
