### ISSUE TITLE
Bold text without spaces leads to ** in document

### ISSUE THREAD

**Issue by synox** [adobe/helix-importer#214]
**Description**
when importing https://www.24life.com/traveling-transformation/

there is the HTML 
```html
<p><strong>THE STAY:</strong>Kulm Hotel St. Moritz &amp; Grand Hotel Kronenhof<br>
```
which causes markdown to produce: 
```md
**THE STAY:**Kulm Hotel St. Moritz & Grand Hotel Kronenhof
```

which turns into the word document: 
![Screenshot 2023-08-23 at 17 21 50](https://github.com/adobe/helix-importer/assets/2250964/df4fd750-50ff-40a8-81d8-db16caedf768)

**To Reproduce**
Run import on that url. 

**Expected behavior**
Importer should handle bold text properly.

**Comment by tripodsan** [comment]
should be fixed with https://github.com/adobe/helix-importer/pull/215

**Comment by synox** [comment]
@tripodsan still happens with 14.24.12
