### ISSUE TITLE
`<i> </i>` generates `**`

### ISSUE THREAD

**Issue by synox** [adobe/helix-importer#217]
**Description**
There are many markdown problems around bold and italics: 

<img width="1058" alt="Screenshot 2023-08-25 at 08 42 13" src="https://github.com/adobe/helix-importer/assets/2250964/7e3aca5b-7066-4be8-b60f-ad0abdad3baa">

### e.g. https://www.24life.com/energy-management-hormones/

- also `<i>,</i>` creates `*,*`
- `<i>”</i>` creates `*”*`

### e.g. https://www.24life.com/sports-specific-training-tennis/
- `<p><strong><em>Side shuffle </em></strong><em>– </em>Quadriceps, glutes, hamstrings, calves</p>` yields `**Side shuffle **– Quadriceps, glutes, hamstrings, calves`
- more similar examples on the same page

### e.g. https://www.24life.com/surprising-superfoods/
`<span>Tip: </span>` -> `**Tip: **`

### e.g. https://www.24life.com/how-to-make-your-trip-to-the-gym-count/
`<p>2.<b><strong> Disconnect from work</strong></b></p>` -> `2.** Disconnect from work**`

### e.g. https://www.24life.com/dynamic-aging-with-katy-bowman/
`<b>24Life: How do you celebrate the end of the year?<br></b>` yields to `**24Life: How do you celebrate the end of the year?**` in the Word document

... and I have more examples where markdown translation breaks... 

**To Reproduce**
import https://www.24life.com/energy-management-hormones/

**Expected behavior**
no `**` in the word document

**Screenshots**
output word doc: 
[energy-management-hormones.docx](https://github.com/adobe/helix-importer/files/12431531/energy-management-hormones.docx)

**Version:**
14.24.12

**Comment by synox** [comment]
@tripodsan see also this one

**Comment by tripodsan** [comment]
`**` is the markdown marker for `<strong>`. the examples above seem to be correct.

**Comment by synox** [comment]
@tripodsan The "yields` are in the word document, I don't think we want to see `**` and *`  there!
