### ISSUE TITLE
Document is parsed twice with JSDOM

### ISSUE THREAD

**Issue by Buuhuu** [adobe/helix-importer#258]
**Is your feature request related to a problem? Please describe.**
For crosswalk we use the html2md in a serverless function. That works fine. However it does not perform very well yet. JSDOM adds about 300ms for the document I am testing.

Having a look at a performance measurement it seems that the importer is running JSDOM twice on the html. 

(1) https://github.com/adobe/helix-importer/blob/main/src/importer/HTML2x.js#L239
(2) https://github.com/adobe/helix-importer/blob/main/src/importer/PageImporter.js#L300

My assumption would be, that if I provide a document object (not a string) to html2md, it is used as is and no further serialisation and reparsing happens. That would also allow us to use different dom parsers depending on the use case or context, e.g.

- not the full feature set of JSDOM is needed we may want to use https://github.com/WebReflection/linkedom (which in my test is significantly faster than using JSDOM)
- in browser we may want to use the native DOMParser

**Describe the solution you'd like**
- ideally we could remove the double parsing using JSDOM

**Describe alternatives you've considered**
- none yet

**Comment by kptdobe** [comment]
This should have been fixed recently. Please re-open if this is still the case.
